"""Compatibility facade for the split reviewed-skill command family.

Attributes remain live views of their owning seam. Assignment is forwarded so
monkeypatching ``brigade.skills_cmd`` changes the callable seen by all
module-reference callers.
"""
# ruff: noqa: F401

from __future__ import annotations

import importlib as _importlib
import sys as _sys
from types import ModuleType
from typing import TYPE_CHECKING
from typing import Any as _Any

_MODULE_NAMES = (
    "registry",
    "search_validate",
    "install",
    "sync_history",
    "packs",
    "adapters",
    "inbox",
)

# These were imports on the original skills_cmd module. Every seam preserves the
# corresponding module global, so facade monkeypatches must be broadcast to
# every seam that binds it.
_SHARED_IMPORT_NAMES = (
    "contextlib",
    "difflib",
    "hashlib",
    "json",
    "os",
    "shlex",
    "shutil",
    "stat_module",
    "sys",
    "tempfile",
    "uuid",
    "dataclass",
    "datetime",
    "timezone",
    "Path",
    "Any",
    "Iterator",
    "Literal",
    "cast",
    "BRIGADE_VERSION",
    "mcp_server",
    "slugify",
    "_now",
    "projection",
    "template_root",
    "scan_untrusted",
)
if TYPE_CHECKING:
    from .registry import (
        BUNDLED_SOURCE_PREFIX,
        FAIL,
        HARNESS_ADAPTERS,
        HARNESS_TARGETS,
        INSTALL_TARGETS,
        OK,
        RECEIPT_SCHEMA_VERSION,
        RENDERER_SCHEMA_VERSION,
        SOURCE_SCHEMA_VERSION,
        SkillsStatePathError,
        TRUST_LEVELS,
        WARN,
        _CLOEXEC,
        _DIR_OPEN_FLAGS,
        _FILE_READ_FLAGS,
        _FILE_REPLACE_FLAGS,
        _HAS_DESCRIPTOR_ANCHOR,
        _O_DIRECTORY,
        _O_NOFOLLOW,
        _O_NONBLOCK,
        _StateRootAnchor,
        _adapters_config_path,
        _anchor_open_chain,
        _anchored_entry_changelog_text,
        _anchored_fs_errors,
        _anchored_load_registry_metadata,
        _anchored_registry_metadata,
        _anchored_registry_text,
        _append_jsonl,
        _append_state_line,
        _bundled_skill_exists,
        _bundled_skill_path,
        _bytes_fingerprint,
        _changelog_payload,
        _codex_frontmatter,
        _codex_frontmatter_values,
        _collect_fd_tree,
        _collect_source_tree,
        _ensure_codex_frontmatter,
        _ensure_hermes_frontmatter,
        _fallback_mutation_refusal,
        _fallback_prepare_parent,
        _file_fingerprint,
        _files_fingerprint,
        _fingerprint,
        _has_yaml_frontmatter,
        _held_state_root,
        _hermes_frontmatter,
        _hermes_frontmatter_values,
        _hermes_home,
        _hermes_skills_root,
        _hold_state_root,
        _inbox_root,
        _install_history_path,
        _installs_root,
        _is_reparse_point,
        _iter_registry,
        _json_bytes,
        _json_string,
        _load_skill,
        _metadata_path,
        _open_state_root_descriptor,
        _plain_subdirs_under_anchor,
        _read_json,
        _read_jsonl,
        _read_registry_entry_tree,
        _read_regular_file_via_fd,
        _read_state_file_bytes,
        _read_tree_from_anchor,
        _registry_entry_present,
        _registry_import_payload,
        _registry_root,
        _remove_tree_in_anchor,
        _render_skill_text_for_harness,
        _rendered_skill_validation,
        _require_plain_state_dirs,
        _require_single_link_regular,
        _resolve_diff_baseline,
        _rm_children_recursive,
        _rollback_root,
        _selects_registry_skill,
        _skill_md_path,
        _skill_packs_archive_root,
        _skill_packs_root,
        _skill_path,
        _slug,
        _source_identity,
        _source_skill_dir,
        _state_entry_kind,
        _state_file_exists,
        _state_json_via_anchor,
        _text_fingerprint,
        _trust_score_payload,
        _unlink_in_anchor,
        _verify_state_root_no_descriptor,
        _write_all_fd,
        _write_collected_tree_into_anchor,
        _write_snapshot_tree,
        _write_state_file,
    )
    from .search_validate import (
        _compatibility_payload,
        _finalize_staged_registry_lint,
        _lint_path_payload,
        _lint_payload,
        _lint_registry_payload,
        _repoint_staged_lint_paths,
        _unreadable_source_lint_payload,
        compatibility,
        import_skill,
        lint,
        search,
    )
    from .install import (
        UserProfileSkillPackage,
        _USER_PROFILE_HARNESSES,
        _USER_PROFILE_MAX_BYTES,
        _USER_PROFILE_MAX_FILES,
        _adapter_map,
        _anchor_subtree_is_plain,
        _dir_fd_subtree_plain,
        _drift_payload,
        _evaluate_install_dir,
        _install_dir,
        _install_history,
        _install_targets,
        _installed_tree_snapshot,
        _latest_install_receipt,
        _previous_install_receipt,
        _renderer_contract,
        _renderer_identity,
        _safe_install_path,
        _snapshot_package_files,
        _user_profile_package,
        _valid_receipt_contract,
        install,
        user_profile_skill_packages,
    )
    from .sync_history import (
        _sync_file_entries,
        _sync_file_mutations,
        _sync_files_fingerprint,
        _sync_plan,
        _sync_projection_plan,
        _sync_recovery_records,
        _sync_rendered_files,
        _sync_single_file_mutation,
        _trust_at_least,
        diff,
        history,
        rollback,
        sync,
        uninstall,
    )
    from .packs import (
        _anchored_pack_manifest,
        _anchored_pack_manifest_at,
        _find_skill_pack,
        _is_under_state_root,
        _lexical_state_root_parts,
        _pack_display,
        _pack_import_from_dir,
        _skill_pack_payload,
        _skill_packs,
        _state_root_selector_kind,
        pack_archive,
        pack_build,
        pack_import,
        pack_list,
        pack_show,
    )
    from .adapters import (
        _fleet_copy_keys,
        _fleet_receipts,
        _fleet_remove_command,
        _fleet_skill_ids,
        _fleet_source_selector,
        _fleet_status_payload,
        _fleet_update_command,
        _mcp_contract_payload,
        _mcp_read_resource,
        _mcp_resource_items,
        _mcp_tool_call,
        _mcp_tool_specs,
        _plain_files_under_anchor,
        _run_mcp_stdio,
        _skill_health_issues,
        _skills_doctor_payload,
        adapters_init,
        adapters_list,
        adapters_show,
        doctor,
        fleet_status,
        publish,
        serve_mcp,
    )
    from .inbox import (
        _anchored_proposals,
        _proposal_meta_path,
        _proposal_skill_path,
        _resolve_proposal,
        _skill_issue_records,
        import_issues,
        inbox_accept,
        inbox_add,
        inbox_diff,
        inbox_list,
        inbox_reject,
        inbox_show,
    )

_OWNERS = {
    "BUNDLED_SOURCE_PREFIX": "registry",
    "FAIL": "registry",
    "HARNESS_ADAPTERS": "registry",
    "HARNESS_TARGETS": "registry",
    "INSTALL_TARGETS": "registry",
    "OK": "registry",
    "RECEIPT_SCHEMA_VERSION": "registry",
    "RENDERER_SCHEMA_VERSION": "registry",
    "SOURCE_SCHEMA_VERSION": "registry",
    "SkillsStatePathError": "registry",
    "TRUST_LEVELS": "registry",
    "UserProfileSkillPackage": "install",
    "WARN": "registry",
    "_CLOEXEC": "registry",
    "_DIR_OPEN_FLAGS": "registry",
    "_FILE_READ_FLAGS": "registry",
    "_FILE_REPLACE_FLAGS": "registry",
    "_HAS_DESCRIPTOR_ANCHOR": "registry",
    "_O_DIRECTORY": "registry",
    "_O_NOFOLLOW": "registry",
    "_O_NONBLOCK": "registry",
    "_StateRootAnchor": "registry",
    "_USER_PROFILE_HARNESSES": "install",
    "_USER_PROFILE_MAX_BYTES": "install",
    "_USER_PROFILE_MAX_FILES": "install",
    "_adapter_map": "install",
    "_adapters_config_path": "registry",
    "_anchor_open_chain": "registry",
    "_anchor_subtree_is_plain": "install",
    "_anchored_entry_changelog_text": "registry",
    "_anchored_fs_errors": "registry",
    "_anchored_load_registry_metadata": "registry",
    "_anchored_pack_manifest": "packs",
    "_anchored_pack_manifest_at": "packs",
    "_anchored_proposals": "inbox",
    "_anchored_registry_metadata": "registry",
    "_anchored_registry_text": "registry",
    "_append_jsonl": "registry",
    "_append_state_line": "registry",
    "_bundled_skill_exists": "registry",
    "_bundled_skill_path": "registry",
    "_bytes_fingerprint": "registry",
    "_changelog_payload": "registry",
    "_codex_frontmatter": "registry",
    "_codex_frontmatter_values": "registry",
    "_collect_fd_tree": "registry",
    "_collect_source_tree": "registry",
    "_compatibility_payload": "search_validate",
    "_dir_fd_subtree_plain": "install",
    "_drift_payload": "install",
    "_ensure_codex_frontmatter": "registry",
    "_ensure_hermes_frontmatter": "registry",
    "_evaluate_install_dir": "install",
    "_fallback_mutation_refusal": "registry",
    "_fallback_prepare_parent": "registry",
    "_file_fingerprint": "registry",
    "_files_fingerprint": "registry",
    "_finalize_staged_registry_lint": "search_validate",
    "_find_skill_pack": "packs",
    "_fingerprint": "registry",
    "_fleet_copy_keys": "adapters",
    "_fleet_receipts": "adapters",
    "_fleet_remove_command": "adapters",
    "_fleet_skill_ids": "adapters",
    "_fleet_source_selector": "adapters",
    "_fleet_status_payload": "adapters",
    "_fleet_update_command": "adapters",
    "_has_yaml_frontmatter": "registry",
    "_held_state_root": "registry",
    "_hermes_frontmatter": "registry",
    "_hermes_frontmatter_values": "registry",
    "_hermes_home": "registry",
    "_hermes_skills_root": "registry",
    "_hold_state_root": "registry",
    "_inbox_root": "registry",
    "_install_dir": "install",
    "_install_history": "install",
    "_install_history_path": "registry",
    "_install_targets": "install",
    "_installed_tree_snapshot": "install",
    "_installs_root": "registry",
    "_is_reparse_point": "registry",
    "_is_under_state_root": "packs",
    "_iter_registry": "registry",
    "_json_bytes": "registry",
    "_json_string": "registry",
    "_latest_install_receipt": "install",
    "_lexical_state_root_parts": "packs",
    "_lint_path_payload": "search_validate",
    "_lint_payload": "search_validate",
    "_lint_registry_payload": "search_validate",
    "_load_skill": "registry",
    "_mcp_contract_payload": "adapters",
    "_mcp_read_resource": "adapters",
    "_mcp_resource_items": "adapters",
    "_mcp_tool_call": "adapters",
    "_mcp_tool_specs": "adapters",
    "_metadata_path": "registry",
    "_open_state_root_descriptor": "registry",
    "_pack_display": "packs",
    "_pack_import_from_dir": "packs",
    "_plain_files_under_anchor": "adapters",
    "_plain_subdirs_under_anchor": "registry",
    "_previous_install_receipt": "install",
    "_proposal_meta_path": "inbox",
    "_proposal_skill_path": "inbox",
    "_read_json": "registry",
    "_read_jsonl": "registry",
    "_read_registry_entry_tree": "registry",
    "_read_regular_file_via_fd": "registry",
    "_read_state_file_bytes": "registry",
    "_read_tree_from_anchor": "registry",
    "_registry_entry_present": "registry",
    "_registry_import_payload": "registry",
    "_registry_root": "registry",
    "_remove_tree_in_anchor": "registry",
    "_render_skill_text_for_harness": "registry",
    "_rendered_skill_validation": "registry",
    "_renderer_contract": "install",
    "_renderer_identity": "install",
    "_repoint_staged_lint_paths": "search_validate",
    "_require_plain_state_dirs": "registry",
    "_require_single_link_regular": "registry",
    "_resolve_diff_baseline": "registry",
    "_resolve_proposal": "inbox",
    "_rm_children_recursive": "registry",
    "_rollback_root": "registry",
    "_run_mcp_stdio": "adapters",
    "_safe_install_path": "install",
    "_selects_registry_skill": "registry",
    "_skill_health_issues": "adapters",
    "_skill_issue_records": "inbox",
    "_skill_md_path": "registry",
    "_skill_pack_payload": "packs",
    "_skill_packs": "packs",
    "_skill_packs_archive_root": "registry",
    "_skill_packs_root": "registry",
    "_skill_path": "registry",
    "_skills_doctor_payload": "adapters",
    "_slug": "registry",
    "_snapshot_package_files": "install",
    "_source_identity": "registry",
    "_source_skill_dir": "registry",
    "_state_entry_kind": "registry",
    "_state_file_exists": "registry",
    "_state_json_via_anchor": "registry",
    "_state_root_selector_kind": "packs",
    "_sync_file_entries": "sync_history",
    "_sync_file_mutations": "sync_history",
    "_sync_files_fingerprint": "sync_history",
    "_sync_plan": "sync_history",
    "_sync_projection_plan": "sync_history",
    "_sync_recovery_records": "sync_history",
    "_sync_rendered_files": "sync_history",
    "_sync_single_file_mutation": "sync_history",
    "_text_fingerprint": "registry",
    "_trust_at_least": "sync_history",
    "_trust_score_payload": "registry",
    "_unlink_in_anchor": "registry",
    "_unreadable_source_lint_payload": "search_validate",
    "_user_profile_package": "install",
    "_valid_receipt_contract": "install",
    "_verify_state_root_no_descriptor": "registry",
    "_write_all_fd": "registry",
    "_write_collected_tree_into_anchor": "registry",
    "_write_snapshot_tree": "registry",
    "_write_state_file": "registry",
    "adapters_init": "adapters",
    "adapters_list": "adapters",
    "adapters_show": "adapters",
    "compatibility": "search_validate",
    "diff": "sync_history",
    "doctor": "adapters",
    "fleet_status": "adapters",
    "history": "sync_history",
    "import_issues": "inbox",
    "import_skill": "search_validate",
    "inbox_accept": "inbox",
    "inbox_add": "inbox",
    "inbox_diff": "inbox",
    "inbox_list": "inbox",
    "inbox_reject": "inbox",
    "inbox_show": "inbox",
    "install": "install",
    "lint": "search_validate",
    "pack_archive": "packs",
    "pack_build": "packs",
    "pack_import": "packs",
    "pack_list": "packs",
    "pack_show": "packs",
    "publish": "adapters",
    "rollback": "sync_history",
    "search": "search_validate",
    "serve_mcp": "adapters",
    "sync": "sync_history",
    "uninstall": "sync_history",
    "user_profile_skill_packages": "install",
}


class _FacadeModule(ModuleType):
    def __getattribute__(self, name: str) -> _Any:
        # Owned names win over a same-named seam module (install.py vs install()).
        owner = _OWNERS.get(name)
        if owner is not None:
            return getattr(_sys.modules[f"{ModuleType.__getattribute__(self, '__name__')}.{owner}"], name)
        return super().__getattribute__(name)

    def __getattr__(self, name: str) -> _Any:
        shared_modules = _SHARED_IMPORTS.get(name)
        if shared_modules:
            return getattr(_sys.modules[f"{self.__name__}.{shared_modules[0]}"], name)
        raise AttributeError(f"module {self.__name__!r} has no attribute {name!r}")

    def __setattr__(self, name: str, value: _Any) -> None:
        owner = _OWNERS.get(name)
        if owner is not None:
            setattr(_sys.modules[f"{self.__name__}.{owner}"], name, value)
            return
        shared_modules = _SHARED_IMPORTS.get(name)
        if shared_modules:
            for module_name in shared_modules:
                setattr(_sys.modules[f"{self.__name__}.{module_name}"], name, value)
            return
        super().__setattr__(name, value)

    def __delattr__(self, name: str) -> None:
        owner = _OWNERS.get(name)
        if owner is not None:
            delattr(_sys.modules[f"{self.__name__}.{owner}"], name)
            return
        shared_modules = _SHARED_IMPORTS.get(name)
        if shared_modules:
            for module_name in shared_modules:
                delattr(_sys.modules[f"{self.__name__}.{module_name}"], name)
            return
        super().__delattr__(name)


for _module_name in _MODULE_NAMES:
    _importlib.import_module(f"{__name__}.{_module_name}")

_SHARED_IMPORTS: dict[str, tuple[str, ...]] = {
    name: tuple(module_name for module_name in _MODULE_NAMES if name in vars(_sys.modules[f"{__name__}.{module_name}"]))
    for name in _SHARED_IMPORT_NAMES
}

_sys.modules[__name__].__class__ = _FacadeModule
