"""Compatibility facade for the split task and import ledger.

Attributes remain live views of their owning seam. Assignment is forwarded so
monkeypatching ``brigade.work_cmd.ledger`` changes the callable seen by all
module-reference callers.
"""
# ruff: noqa: F401

from __future__ import annotations

import importlib as _importlib
import sys as _sys
from types import ModuleType
from typing import TYPE_CHECKING
from typing import Any as _Any

_MODULE_NAMES = (
    "locking",
    "import_model",
    "authority_store",
    "descriptor_anchors",
    "inbox_provenance",
    "queries_handoffs",
    "tasks_plans",
)

# These were imports on the original ledger module. Every seam preserves the
# corresponding module global, so facade monkeypatches must be broadcast to
# every seam that binds it.
_SHARED_IMPORT_NAMES = (
    "hashlib",
    "json",
    "math",
    "os",
    "re",
    "shutil",
    "stat",
    "subprocess",
    "sys",
    "time",
    "contextmanager",
    "datetime",
    "Path",
    "Any",
    "Callable",
    "Iterator",
    "Mapping",
    "Sequence",
    "cast",
    "uuid4",
    "constants",
    "edges_mod",
    "helpers",
    "inbox_lock",
    "verify_canonical_write_locks",
    "component_paths",
    "evidence_redaction",
    "provenance",
    "runguard",
    "trust_gate",
    "scan_handoff_injection_heuristics",
)
if TYPE_CHECKING:
    from .authority_store import (
        _adopt_legacy_directory_authority_if_safe,
        _authority_hmac_enabled,
        _authority_record_mismatch_error,
        _authority_target_digest,
        _authority_workspace_from_record,
        _directory_authority_rebind_command,
        _directory_authority_scope,
        _directory_authority_store_path,
        _directory_identity,
        _dirfd_available,
        _dirfd_fsync,
        _dirfd_mkdir,
        _dirfd_open_dir,
        _dirfd_open_file,
        _dirfd_replace,
        _dirfd_stat,
        _dirfd_unavailable,
        _dirfd_unlink,
        _downgrade_durability_checkpoint,
        _external_workspace_directory_identity,
        _format_authority_field_value,
        _is_legacy_external_directory_authority,
        _live_directory_scope_mismatches,
        _nt_dirfd_available,
        _open_directory_nofollow,
        _open_file_nofollow,
        _posix_dirfd_available,
        _present_directory_authority_mismatches,
        _publish_authority_store_payload,
        _read_external_directory_authority,
        _read_external_directory_authority_path,
        _read_raw_authority_store,
        _reanchor_external_directory_authority,
        _record_external_directory_authority,
        _require_workspace_directory_identity,
        _restore_authority_file,
        _unwrap_authority_envelope,
        _upgrade_legacy_directory_authority,
        _validate_external_directory_authority,
        _workspace_directory_identity,
        _write_external_directory_authority,
        downgrade_external_directory_authority,
        rebind_directory_authority,
    )
    from .descriptor_anchors import (
        _APPEND_SNAPSHOT_ABSENT,
        _UNSIGNED_DEDUPE_DOWNGRADE_WARNED,
        _acquire_authenticated_authority_snapshot,
        _adopt_preexisting_scanner_run_directories,
        _authenticated_legacy_import_proof,
        _authority_store_binding_is_verifier_signed,
        _external_file_authorities,
        _file_identity,
        _has_local_import_envelope,
        _has_locally_stamped_import_proof,
        _has_persisted_import_proof,
        _import_content_identity,
        _open_import_proof_directory,
        _open_legacy_scanner_runs_directory,
        _open_verifier_owned_directory,
        _persisted_import_proof_payload,
        _persisted_import_proof_scopes,
        _read_local_scanner_receipt,
        _read_verified_authority_snapshot,
        _record_verifier_owned_directory,
        _record_verifier_owned_file,
        _remove_persisted_import_proofs,
        _restore_external_file_authorities,
        _snapshot_external_file_authorities,
        _unsigned_dedupe_proof_for_non_isolated_workspace,
        _validate_import_proof_descriptor,
        _validate_import_proof_name_matches_descriptor,
        _validate_record_bound_directory,
        _validate_verifier_owned_directory,
        _validate_verifier_owned_file,
        _write_compatibility_directory_anchor,
        _write_persisted_import_proofs,
    )
    from .import_model import (
        _DIRECTORY_AUTHORITY_SCHEMA_VERSION,
        _EXTERNAL_DIRECTORY_AUTHORITY_SCHEMA_VERSION,
        _IMPORT_PROOF_OPERATION_PATTERN,
        _IMPORT_PROOF_SCHEMA_VERSION,
        _LocallyStampedImportProof,
        _ReviewedImportSnapshot,
        _UNTRUSTED_IMPORT_IDENTITY_METADATA_KEYS,
        _UNTRUSTED_IMPORT_OPERATIONAL_METADATA_KEYS,
        _UNTRUSTED_IMPORT_PROVENANCE_METADATA_KEYS,
        _append_archived_imports,
        _bound_declared_import_alias,
        _capture_reviewed_import_snapshot,
        _combined_acceptance,
        _confidence_rank,
        _dispatch_annotations,
        _extract_issue_acceptance,
        _github_issue_ref,
        _handoff_candidate,
        _handoff_ready_imports,
        _has_canonical_untrusted_import_identity,
        _import_context,
        _import_inbox_digest,
        _import_proof_name,
        _import_record_key,
        _import_sort_key,
        _import_source_key,
        _import_summary,
        _import_task_acceptance,
        _import_task_priority,
        _import_task_template,
        _import_task_type,
        _is_issue_acceptance_heading,
        _is_locally_stamped_self_import,
        _is_untrusted_import_metadata_key_allowed,
        _issue_heading,
        _issue_list_item,
        _issue_repair_record,
        _issue_repair_records,
        _locally_stamped_import_content_hash,
        _make_locally_stamped_import_proof,
        _merge_dispatch_annotations,
        _normalize_acceptance,
        _normalize_issue_heading,
        _normalize_seat_class,
        _normalize_spend_by,
        _normalize_task_priority,
        _normalize_task_type,
        _parse_import_inbox_bytes,
        _read_github_issue,
        _read_import_inbox_raw,
        _read_imports,
        _safe_issue_task_id,
        _safe_self_import_document_target,
        _safe_self_import_path,
        _safe_self_import_source_item_key,
        _safe_stable_source_fingerprint,
        _sanitize_dispatch_metadata,
        _sanitize_self_import_record,
        _sanitize_untrusted_import_metadata,
        _sanitize_untrusted_import_record,
        _scanner_candidate,
        _stale_claim_payload,
        _string_field,
        _task_acceptance,
        _task_issue_metadata,
        _task_preview_from_import,
        _task_snapshot,
        _task_sort_key,
        _task_summary,
        _task_text_key,
        _template_acceptance,
        _trusted_self_import_metadata,
        _untrusted_import_canonical_hash,
        _write_imports,
    )
    from .inbox_provenance import (
        _IMPORT_CAPTURED_AT_MAX_LEN,
        _IMPORT_FINGERPRINT_METADATA_SKIP,
        _IMPORT_IDENTITY_MAX_LEN,
        _IMPORT_PROVENANCE_REJECTION_REASON,
        _IMPORT_SOURCE_ORIGIN_MODALITY,
        _ImportProvenanceError,
        _append_import_records,
        _append_import_records_locked,
        _backfill_import_provenance,
        _backfill_import_provenance_locked,
        _bound_import_identity,
        _import_envelope_matches,
        _import_fingerprint,
        _import_injection_trust,
        _import_origin_modality,
        _import_repository_fields,
        _import_session_fields,
        _import_source_identity,
        _legacy_import_source_content_identity,
        _load_import_jsonl,
        _locator_is_unsafe,
        _open_import_inbox_parent,
        _open_import_inbox_parent_nt,
        _open_import_inbox_parent_posix,
        _parse_import_jsonl,
        _repository_id_is_unsafe,
        _resolve_import_provenance_source,
        _restore_import_inbox_snapshot,
        _reusable_inbound_provenance,
        _safe_import_identity,
        _safe_locator_fields,
        _safe_repository_id,
        _safe_repository_revision,
        _sanitize_import_identity_metadata,
        _snapshot_import_inbox,
        _stamp_import_provenance,
        _stamp_inferred_import_provenance,
        _validate_import_inbox_descriptor,
        _validate_import_inbox_name_matches_descriptor,
        _validate_import_record,
        _write_import_inbox_bytes_at,
    )
    from .locking import (
        ImportInboxSnapshotLimitExceeded,
        REASON_CORRUPT_LEDGER,
        REASON_IMPORT_SNAPSHOT_CHANGED,
        REASON_TRUST_POLICY,
        REASON_UNSUPPORTED_LEDGER_VERSION,
        SCANNER_CHILD_TASK_LEDGER_LOCK_DEADLINE_SECONDS,
        TASK_LEDGER_LOCK_DEADLINE_SECONDS,
        TaskLedgerError,
        TaskLedgerLockTimeout,
        _IMPORT_INBOX_SNAPSHOT_LIMIT_BYTES,
        _TASK_LEDGER_LOCK_RETRY_INTERVAL_SECONDS,
        _acquire_task_ledger_lock,
        _canonical_inbox_write,
        _claim_task,
        _read_task_ledger,
        _reassign_task,
        _release_tasks,
        _task_ledger_lock,
        _task_ledger_lock_deadline_seconds,
        _task_ledger_lock_path,
        _write_task_ledger,
        emit_task_ledger_error,
        guard_task_ledger_dispatch,
    )
    from .queries_handoffs import (
        _PROVENANCE_ENVELOPE_KEYS,
        _PROVENANCE_HASHES_KEYS,
        _PROVENANCE_INJECTION_KEYS,
        _PROVENANCE_LOCATOR_KEYS,
        _PROVENANCE_REDACTION_KEYS,
        _PROVENANCE_REPOSITORY_KEYS,
        _PROVENANCE_SESSION_KEYS,
        _PROVENANCE_SOURCE_KEYS,
        _PROVENANCE_TRUST_KEYS,
        _PROVENANCE_TRUST_POLICY_KEYS,
        _after_batch_import_promote_applied,
        _after_reviewed_import_snapshot,
        _authorize_task_start,
        _evaluate_task_start_gates,
        _find_import,
        _find_pending_task_by_text,
        _handoff_is_document_target,
        _handoff_private_fields,
        _handoff_private_fields_in_validated_provenance,
        _handoff_provenance,
        _handoff_redact_value,
        _handoff_render_value,
        _handoff_safe_text,
        _handoff_suggested_document_content,
        _handoff_target_document,
        _handoff_title,
        _handoff_type,
        _import_counts,
        _import_handoff_plan_payload,
        _import_item_content_digest,
        _import_metadata_matches,
        _import_snapshot_join_set,
        _import_trust_blocker,
        _mark_import_handoff_promoted,
        _mark_import_promoted,
        _matching_pending_imports,
        _parse_metadata_filters,
        _parse_or_report_metadata_filters,
        _pending_imports,
        _pending_imports_from_items,
        _pending_tasks,
        _promote_matching_imports,
        _promote_matching_imports_locked,
        _readiness_payload,
        _ready_tasks,
        _render_import_handoff,
        _require_reviewed_import_snapshot,
        _startable_tasks,
        _write_import_handoff,
    )
    from .tasks_plans import (
        DECISION_RECEIPT_KEYS,
        DECISION_STATUS_PENDING,
        DECISION_STATUS_RESOLVED,
        PLAN_RECEIPT_SCHEMA,
        PlanDecisionError,
        REASON_CORRUPT_PLAN_RECEIPT,
        REASON_MALFORMED_PLAN_DECISIONS,
        REASON_MISSING_PLAN_RECEIPT,
        REASON_PLAN_RECEIPT_MISMATCH,
        _DECISION_ID_RE,
        _add_task,
        _annotate_task,
        _append_dedupe,
        _apply_add_task_to_ledger,
        _apply_graph_plan,
        _build_plan_receipt,
        _decision_gate_message,
        _decision_is_resolved,
        _declare_plan_decision,
        _find_task,
        _load_plan_receipt,
        _make_import,
        _make_task,
        _normalize_decision_entry,
        _normalize_decision_id,
        _normalize_decisions,
        _parse_metadata,
        _plan_artifact_summary,
        _plan_coverage_payload,
        _plan_decisions,
        _plan_receipt_digest,
        _plan_rel_path,
        _read_plan_receipt,
        _render_plan_md,
        _resolve_plan_decision,
        _significant_pending_without_plan,
        _task_plan_binding,
        _unresolved_decisions,
        _unresolved_plan_decisions,
        _validate_decision_entry_field_types,
        _verify_plan_receipt_digest,
        _verify_plan_receipt_identity,
        _write_plan_artifact,
    )

_OWNERS = {
    "DECISION_RECEIPT_KEYS": "tasks_plans",
    "DECISION_STATUS_PENDING": "tasks_plans",
    "DECISION_STATUS_RESOLVED": "tasks_plans",
    "ImportInboxSnapshotLimitExceeded": "locking",
    "PLAN_RECEIPT_SCHEMA": "tasks_plans",
    "PlanDecisionError": "tasks_plans",
    "REASON_CORRUPT_LEDGER": "locking",
    "REASON_CORRUPT_PLAN_RECEIPT": "tasks_plans",
    "REASON_IMPORT_SNAPSHOT_CHANGED": "locking",
    "REASON_MALFORMED_PLAN_DECISIONS": "tasks_plans",
    "REASON_MISSING_PLAN_RECEIPT": "tasks_plans",
    "REASON_PLAN_RECEIPT_MISMATCH": "tasks_plans",
    "REASON_TRUST_POLICY": "locking",
    "REASON_UNSUPPORTED_LEDGER_VERSION": "locking",
    "SCANNER_CHILD_TASK_LEDGER_LOCK_DEADLINE_SECONDS": "locking",
    "TASK_LEDGER_LOCK_DEADLINE_SECONDS": "locking",
    "TaskLedgerError": "locking",
    "TaskLedgerLockTimeout": "locking",
    "_APPEND_SNAPSHOT_ABSENT": "descriptor_anchors",
    "_DECISION_ID_RE": "tasks_plans",
    "_DIRECTORY_AUTHORITY_SCHEMA_VERSION": "import_model",
    "_EXTERNAL_DIRECTORY_AUTHORITY_SCHEMA_VERSION": "import_model",
    "_IMPORT_CAPTURED_AT_MAX_LEN": "inbox_provenance",
    "_IMPORT_FINGERPRINT_METADATA_SKIP": "inbox_provenance",
    "_IMPORT_IDENTITY_MAX_LEN": "inbox_provenance",
    "_IMPORT_INBOX_SNAPSHOT_LIMIT_BYTES": "locking",
    "_IMPORT_PROOF_OPERATION_PATTERN": "import_model",
    "_IMPORT_PROOF_SCHEMA_VERSION": "import_model",
    "_IMPORT_PROVENANCE_REJECTION_REASON": "inbox_provenance",
    "_IMPORT_SOURCE_ORIGIN_MODALITY": "inbox_provenance",
    "_ImportProvenanceError": "inbox_provenance",
    "_LocallyStampedImportProof": "import_model",
    "_PROVENANCE_ENVELOPE_KEYS": "queries_handoffs",
    "_PROVENANCE_HASHES_KEYS": "queries_handoffs",
    "_PROVENANCE_INJECTION_KEYS": "queries_handoffs",
    "_PROVENANCE_LOCATOR_KEYS": "queries_handoffs",
    "_PROVENANCE_REDACTION_KEYS": "queries_handoffs",
    "_PROVENANCE_REPOSITORY_KEYS": "queries_handoffs",
    "_PROVENANCE_SESSION_KEYS": "queries_handoffs",
    "_PROVENANCE_SOURCE_KEYS": "queries_handoffs",
    "_PROVENANCE_TRUST_KEYS": "queries_handoffs",
    "_PROVENANCE_TRUST_POLICY_KEYS": "queries_handoffs",
    "_ReviewedImportSnapshot": "import_model",
    "_TASK_LEDGER_LOCK_RETRY_INTERVAL_SECONDS": "locking",
    "_UNSIGNED_DEDUPE_DOWNGRADE_WARNED": "descriptor_anchors",
    "_UNTRUSTED_IMPORT_IDENTITY_METADATA_KEYS": "import_model",
    "_UNTRUSTED_IMPORT_OPERATIONAL_METADATA_KEYS": "import_model",
    "_UNTRUSTED_IMPORT_PROVENANCE_METADATA_KEYS": "import_model",
    "_acquire_authenticated_authority_snapshot": "descriptor_anchors",
    "_acquire_task_ledger_lock": "locking",
    "_add_task": "tasks_plans",
    "_adopt_legacy_directory_authority_if_safe": "authority_store",
    "_adopt_preexisting_scanner_run_directories": "descriptor_anchors",
    "_after_batch_import_promote_applied": "queries_handoffs",
    "_after_reviewed_import_snapshot": "queries_handoffs",
    "_annotate_task": "tasks_plans",
    "_append_archived_imports": "import_model",
    "_append_dedupe": "tasks_plans",
    "_append_import_records": "inbox_provenance",
    "_append_import_records_locked": "inbox_provenance",
    "_apply_add_task_to_ledger": "tasks_plans",
    "_apply_graph_plan": "tasks_plans",
    "_authenticated_legacy_import_proof": "descriptor_anchors",
    "_authority_hmac_enabled": "authority_store",
    "_authority_record_mismatch_error": "authority_store",
    "_authority_store_binding_is_verifier_signed": "descriptor_anchors",
    "_authority_target_digest": "authority_store",
    "_authority_workspace_from_record": "authority_store",
    "_authorize_task_start": "queries_handoffs",
    "_backfill_import_provenance": "inbox_provenance",
    "_backfill_import_provenance_locked": "inbox_provenance",
    "_bound_declared_import_alias": "import_model",
    "_bound_import_identity": "inbox_provenance",
    "_build_plan_receipt": "tasks_plans",
    "_canonical_inbox_write": "locking",
    "_capture_reviewed_import_snapshot": "import_model",
    "_claim_task": "locking",
    "_combined_acceptance": "import_model",
    "_confidence_rank": "import_model",
    "_decision_gate_message": "tasks_plans",
    "_decision_is_resolved": "tasks_plans",
    "_declare_plan_decision": "tasks_plans",
    "_directory_authority_rebind_command": "authority_store",
    "_directory_authority_scope": "authority_store",
    "_directory_authority_store_path": "authority_store",
    "_directory_identity": "authority_store",
    "_dirfd_available": "authority_store",
    "_dirfd_fsync": "authority_store",
    "_dirfd_mkdir": "authority_store",
    "_dirfd_open_dir": "authority_store",
    "_dirfd_open_file": "authority_store",
    "_dirfd_replace": "authority_store",
    "_dirfd_stat": "authority_store",
    "_dirfd_unavailable": "authority_store",
    "_dirfd_unlink": "authority_store",
    "_dispatch_annotations": "import_model",
    "_downgrade_durability_checkpoint": "authority_store",
    "_evaluate_task_start_gates": "queries_handoffs",
    "_external_file_authorities": "descriptor_anchors",
    "_external_workspace_directory_identity": "authority_store",
    "_extract_issue_acceptance": "import_model",
    "_file_identity": "descriptor_anchors",
    "_find_import": "queries_handoffs",
    "_find_pending_task_by_text": "queries_handoffs",
    "_find_task": "tasks_plans",
    "_format_authority_field_value": "authority_store",
    "_github_issue_ref": "import_model",
    "_handoff_candidate": "import_model",
    "_handoff_is_document_target": "queries_handoffs",
    "_handoff_private_fields": "queries_handoffs",
    "_handoff_private_fields_in_validated_provenance": "queries_handoffs",
    "_handoff_provenance": "queries_handoffs",
    "_handoff_ready_imports": "import_model",
    "_handoff_redact_value": "queries_handoffs",
    "_handoff_render_value": "queries_handoffs",
    "_handoff_safe_text": "queries_handoffs",
    "_handoff_suggested_document_content": "queries_handoffs",
    "_handoff_target_document": "queries_handoffs",
    "_handoff_title": "queries_handoffs",
    "_handoff_type": "queries_handoffs",
    "_has_canonical_untrusted_import_identity": "import_model",
    "_has_local_import_envelope": "descriptor_anchors",
    "_has_locally_stamped_import_proof": "descriptor_anchors",
    "_has_persisted_import_proof": "descriptor_anchors",
    "_import_content_identity": "descriptor_anchors",
    "_import_context": "import_model",
    "_import_counts": "queries_handoffs",
    "_import_envelope_matches": "inbox_provenance",
    "_import_fingerprint": "inbox_provenance",
    "_import_handoff_plan_payload": "queries_handoffs",
    "_import_inbox_digest": "import_model",
    "_import_injection_trust": "inbox_provenance",
    "_import_item_content_digest": "queries_handoffs",
    "_import_metadata_matches": "queries_handoffs",
    "_import_origin_modality": "inbox_provenance",
    "_import_proof_name": "import_model",
    "_import_record_key": "import_model",
    "_import_repository_fields": "inbox_provenance",
    "_import_session_fields": "inbox_provenance",
    "_import_snapshot_join_set": "queries_handoffs",
    "_import_sort_key": "import_model",
    "_import_source_identity": "inbox_provenance",
    "_import_source_key": "import_model",
    "_import_summary": "import_model",
    "_import_task_acceptance": "import_model",
    "_import_task_priority": "import_model",
    "_import_task_template": "import_model",
    "_import_task_type": "import_model",
    "_import_trust_blocker": "queries_handoffs",
    "_is_issue_acceptance_heading": "import_model",
    "_is_legacy_external_directory_authority": "authority_store",
    "_is_locally_stamped_self_import": "import_model",
    "_is_untrusted_import_metadata_key_allowed": "import_model",
    "_issue_heading": "import_model",
    "_issue_list_item": "import_model",
    "_issue_repair_record": "import_model",
    "_issue_repair_records": "import_model",
    "_legacy_import_source_content_identity": "inbox_provenance",
    "_live_directory_scope_mismatches": "authority_store",
    "_load_import_jsonl": "inbox_provenance",
    "_load_plan_receipt": "tasks_plans",
    "_locally_stamped_import_content_hash": "import_model",
    "_locator_is_unsafe": "inbox_provenance",
    "_make_import": "tasks_plans",
    "_make_locally_stamped_import_proof": "import_model",
    "_make_task": "tasks_plans",
    "_mark_import_handoff_promoted": "queries_handoffs",
    "_mark_import_promoted": "queries_handoffs",
    "_matching_pending_imports": "queries_handoffs",
    "_merge_dispatch_annotations": "import_model",
    "_normalize_acceptance": "import_model",
    "_normalize_decision_entry": "tasks_plans",
    "_normalize_decision_id": "tasks_plans",
    "_normalize_decisions": "tasks_plans",
    "_normalize_issue_heading": "import_model",
    "_normalize_seat_class": "import_model",
    "_normalize_spend_by": "import_model",
    "_normalize_task_priority": "import_model",
    "_normalize_task_type": "import_model",
    "_nt_dirfd_available": "authority_store",
    "_open_directory_nofollow": "authority_store",
    "_open_file_nofollow": "authority_store",
    "_open_import_inbox_parent": "inbox_provenance",
    "_open_import_inbox_parent_nt": "inbox_provenance",
    "_open_import_inbox_parent_posix": "inbox_provenance",
    "_open_import_proof_directory": "descriptor_anchors",
    "_open_legacy_scanner_runs_directory": "descriptor_anchors",
    "_open_verifier_owned_directory": "descriptor_anchors",
    "_parse_import_inbox_bytes": "import_model",
    "_parse_import_jsonl": "inbox_provenance",
    "_parse_metadata": "tasks_plans",
    "_parse_metadata_filters": "queries_handoffs",
    "_parse_or_report_metadata_filters": "queries_handoffs",
    "_pending_imports": "queries_handoffs",
    "_pending_imports_from_items": "queries_handoffs",
    "_pending_tasks": "queries_handoffs",
    "_persisted_import_proof_payload": "descriptor_anchors",
    "_persisted_import_proof_scopes": "descriptor_anchors",
    "_plan_artifact_summary": "tasks_plans",
    "_plan_coverage_payload": "tasks_plans",
    "_plan_decisions": "tasks_plans",
    "_plan_receipt_digest": "tasks_plans",
    "_plan_rel_path": "tasks_plans",
    "_posix_dirfd_available": "authority_store",
    "_present_directory_authority_mismatches": "authority_store",
    "_promote_matching_imports": "queries_handoffs",
    "_promote_matching_imports_locked": "queries_handoffs",
    "_publish_authority_store_payload": "authority_store",
    "_read_external_directory_authority": "authority_store",
    "_read_external_directory_authority_path": "authority_store",
    "_read_github_issue": "import_model",
    "_read_import_inbox_raw": "import_model",
    "_read_imports": "import_model",
    "_read_local_scanner_receipt": "descriptor_anchors",
    "_read_plan_receipt": "tasks_plans",
    "_read_raw_authority_store": "authority_store",
    "_read_task_ledger": "locking",
    "_read_verified_authority_snapshot": "descriptor_anchors",
    "_readiness_payload": "queries_handoffs",
    "_ready_tasks": "queries_handoffs",
    "_reanchor_external_directory_authority": "authority_store",
    "_reassign_task": "locking",
    "_record_external_directory_authority": "authority_store",
    "_record_verifier_owned_directory": "descriptor_anchors",
    "_record_verifier_owned_file": "descriptor_anchors",
    "_release_tasks": "locking",
    "_remove_persisted_import_proofs": "descriptor_anchors",
    "_render_import_handoff": "queries_handoffs",
    "_render_plan_md": "tasks_plans",
    "_repository_id_is_unsafe": "inbox_provenance",
    "_require_reviewed_import_snapshot": "queries_handoffs",
    "_require_workspace_directory_identity": "authority_store",
    "_resolve_import_provenance_source": "inbox_provenance",
    "_resolve_plan_decision": "tasks_plans",
    "_restore_authority_file": "authority_store",
    "_restore_external_file_authorities": "descriptor_anchors",
    "_restore_import_inbox_snapshot": "inbox_provenance",
    "_reusable_inbound_provenance": "inbox_provenance",
    "_safe_import_identity": "inbox_provenance",
    "_safe_issue_task_id": "import_model",
    "_safe_locator_fields": "inbox_provenance",
    "_safe_repository_id": "inbox_provenance",
    "_safe_repository_revision": "inbox_provenance",
    "_safe_self_import_document_target": "import_model",
    "_safe_self_import_path": "import_model",
    "_safe_self_import_source_item_key": "import_model",
    "_safe_stable_source_fingerprint": "import_model",
    "_sanitize_dispatch_metadata": "import_model",
    "_sanitize_import_identity_metadata": "inbox_provenance",
    "_sanitize_self_import_record": "import_model",
    "_sanitize_untrusted_import_metadata": "import_model",
    "_sanitize_untrusted_import_record": "import_model",
    "_scanner_candidate": "import_model",
    "_significant_pending_without_plan": "tasks_plans",
    "_snapshot_external_file_authorities": "descriptor_anchors",
    "_snapshot_import_inbox": "inbox_provenance",
    "_stale_claim_payload": "import_model",
    "_stamp_import_provenance": "inbox_provenance",
    "_stamp_inferred_import_provenance": "inbox_provenance",
    "_startable_tasks": "queries_handoffs",
    "_string_field": "import_model",
    "_task_acceptance": "import_model",
    "_task_issue_metadata": "import_model",
    "_task_ledger_lock": "locking",
    "_task_ledger_lock_deadline_seconds": "locking",
    "_task_ledger_lock_path": "locking",
    "_task_plan_binding": "tasks_plans",
    "_task_preview_from_import": "import_model",
    "_task_snapshot": "import_model",
    "_task_sort_key": "import_model",
    "_task_summary": "import_model",
    "_task_text_key": "import_model",
    "_template_acceptance": "import_model",
    "_trusted_self_import_metadata": "import_model",
    "_unresolved_decisions": "tasks_plans",
    "_unresolved_plan_decisions": "tasks_plans",
    "_unsigned_dedupe_proof_for_non_isolated_workspace": "descriptor_anchors",
    "_untrusted_import_canonical_hash": "import_model",
    "_unwrap_authority_envelope": "authority_store",
    "_upgrade_legacy_directory_authority": "authority_store",
    "_validate_decision_entry_field_types": "tasks_plans",
    "_validate_external_directory_authority": "authority_store",
    "_validate_import_inbox_descriptor": "inbox_provenance",
    "_validate_import_inbox_name_matches_descriptor": "inbox_provenance",
    "_validate_import_proof_descriptor": "descriptor_anchors",
    "_validate_import_proof_name_matches_descriptor": "descriptor_anchors",
    "_validate_import_record": "inbox_provenance",
    "_validate_record_bound_directory": "descriptor_anchors",
    "_validate_verifier_owned_directory": "descriptor_anchors",
    "_validate_verifier_owned_file": "descriptor_anchors",
    "_verify_plan_receipt_digest": "tasks_plans",
    "_verify_plan_receipt_identity": "tasks_plans",
    "_workspace_directory_identity": "authority_store",
    "_write_compatibility_directory_anchor": "descriptor_anchors",
    "_write_external_directory_authority": "authority_store",
    "_write_import_handoff": "queries_handoffs",
    "_write_import_inbox_bytes_at": "inbox_provenance",
    "_write_imports": "import_model",
    "_write_persisted_import_proofs": "descriptor_anchors",
    "_write_plan_artifact": "tasks_plans",
    "_write_task_ledger": "locking",
    "downgrade_external_directory_authority": "authority_store",
    "emit_task_ledger_error": "locking",
    "guard_task_ledger_dispatch": "locking",
    "rebind_directory_authority": "authority_store",
}


class _FacadeModule(ModuleType):
    def __getattr__(self, name: str) -> _Any:
        owner = _OWNERS.get(name)
        if owner is not None:
            return getattr(_sys.modules[f"{self.__name__}.{owner}"], name)
        shared_modules = _SHARED_IMPORTS.get(name)
        if shared_modules:
            return getattr(_sys.modules[f"{self.__name__}.{shared_modules[0]}"], name)
        raise AttributeError(f"module {self.__name__!r} has no attribute {name!r}")

    def __setattr__(self, name: str, value: _Any) -> None:
        owner = _OWNERS.get(name)
        if owner is not None:
            setattr(_sys.modules[f"{self.__name__}.{owner}"], name, value)
            return
        shared_modules = _SHARED_IMPORTS.get(name)
        if shared_modules:
            for module_name in shared_modules:
                setattr(_sys.modules[f"{self.__name__}.{module_name}"], name, value)
            return
        super().__setattr__(name, value)

    def __delattr__(self, name: str) -> None:
        owner = _OWNERS.get(name)
        if owner is not None:
            delattr(_sys.modules[f"{self.__name__}.{owner}"], name)
            return
        shared_modules = _SHARED_IMPORTS.get(name)
        if shared_modules:
            for module_name in shared_modules:
                delattr(_sys.modules[f"{self.__name__}.{module_name}"], name)
            return
        super().__delattr__(name)


for _module_name in _MODULE_NAMES:
    _importlib.import_module(f"{__name__}.{_module_name}")

_SHARED_IMPORTS: dict[str, tuple[str, ...]] = {
    name: tuple(module_name for module_name in _MODULE_NAMES if name in vars(_sys.modules[f"{__name__}.{module_name}"]))
    for name in _SHARED_IMPORT_NAMES
}

_sys.modules[__name__].__class__ = _FacadeModule
