r"""Guard the work_cmd package facade surface.

The work_cmd package split (docs/work-cmd-split-plan.md) relies on the
facade re-exporting every name that external modules and tests reference as
``work_cmd.X``. This list was derived from
``grep -rhoE 'work_cmd\.[A-Za-z_][A-Za-z0-9_]*' src/brigade/*.py tests/*.py``
at split time and is frozen here so a re-export regression fails loudly.
"""

from brigade import work_cmd

EXPECTED_FACADE_SYMBOLS = (
    "DISMISSED_SOURCE_WARN_THRESHOLD",
    "SCANNER_HIGH_RISK_COMMANDS",
    "SCANNER_SHELL_META_RE",
    "TASK_TEMPLATES",
    "_acceptance_payload",
    "_active_session_info",
    "_add_task",
    "_append_import_records",
    "_backup_config_path",
    "_backup_health",
    "_brief_payload",
    "_chat_sweep_records",
    "_collect_sessions",
    "_extract_issue_acceptance",
    "_find_sweep_report",
    "_find_task",
    "_git_snapshot",
    "_import_fingerprint",
    "_import_source_identity",
    "_import_summary",
    "_imports_path",
    "_inbox_hygiene_payload",
    "_inbox_quality_payload",
    "_latest_verify_receipt",
    "_latest_work_closeout_payload",
    "_make_import",
    "_mark_import_promoted",
    "_parse_iso_datetime",
    "_pending_imports",
    "_pending_tasks",
    "_plan_coverage_payload",
    "_plan_paths",
    "_plan_proposals_dir",
    "_proposal_path",
    "_read_imports",
    "_read_task_ledger",
    "_review_config_path",
    "_review_health",
    "_review_receipts",
    "_scanner_argv",
    "_scanner_config_path",
    "_scanner_receipts",
    "_scanner_run_summary",
    "_scanner_sweep_health",
    "_scanner_sweeps",
    "_short",
    "_significant_pending_without_plan",
    "_stable_hash",
    "_sweep_review_payload",
    "_task_acceptance",
    "_tasks_path",
    "_verify_receipts",
    "_write_imports",
    "_write_json",
    "_write_sweep_report",
    "_write_task_ledger",
    "acceptance",
    "backup_closeout",
    "backup_contract",
    "backup_doctor",
    "backup_import_issues",
    "backup_init",
    "backup_status",
    "bootstrap",
    "brief",
    "closeout",
    "doctor",
    "end",
    "helpers",
    "import_add",
    "import_chat_sweep",
    "import_content_guard",
    "import_context",
    "import_dismiss",
    "import_ingest",
    "import_issue_repairs",
    "import_list",
    "import_memory_care",
    "import_memory_refresh",
    "import_plan",
    "import_plan_handoff",
    "import_promote",
    "import_promote_handoff",
    "import_provenance",
    "import_show",
    "import_triage",
    "import_validate",
    "inbox",
    "inbox_archive",
    "inbox_doctor",
    "latest",
    "list_sessions",
    "next",
    "note",
    "plan_promote",
    "plan_proposals",
    "plans",
    "recap",
    "resume",
    "review_closeout",
    "review_finding_show",
    "review_findings",
    "review_import_findings",
    "review_init",
    "review_plan",
    "review_run",
    "review_runs",
    "review_show",
    "run",
    "scanners_doctor",
    "scanners_init",
    "scanners_list",
    "scanners_plan",
    "scanners_run",
    "scanners_run_show",
    "scanners_runs",
    "scanners_show",
    "show",
    "start",
    "status",
    "sweep",
    "sweep_closeout",
    "sweep_review",
    "sweep_show",
    "sweeps",
    "task_add",
    "task_done",
    "task_plan",
    "task_show",
    "tasks",
    "verify_plan",
    "verify_run",
    "verify_runs",
    "verify_show",
)


def test_facade_exposes_externally_referenced_symbols():
    missing = [name for name in EXPECTED_FACADE_SYMBOLS if not hasattr(work_cmd, name)]
    assert missing == []


def test_facade_submodules_importable():
    from brigade.work_cmd import config, constants, helpers, ledger, services, session

    for module in (constants, helpers, ledger, config, services, session):
        assert module.__name__.startswith("brigade.work_cmd.")
