r"""Guard the tools_cmd package facade surface.

The tools_cmd package split relies on the facade re-exporting every name that
external modules and tests reference as ``tools_cmd.X``. This list was derived
from explicit aliases in ``tools_cmd.__init__`` at split time and is frozen here
so a re-export regression fails loudly.
"""

from brigade import tools_cmd

EXPECTED_FACADE_SYMBOLS = (
    "OK",
    "WARN",
    "FAIL",
    "CONFIG_REL_PATH",
    "CALLS_REL_PATH",
    "RUNS_REL_PATH",
    "CHECKPOINTS_REL_PATH",
    "RUNTIMES_REL_PATH",
    "RUNTIME_STATE_REL_PATH",
    "POLICY_REL_PATH",
    "PARITY_CLOSEOUTS_REL_PATH",
    "HEALTH_STALE_HOURS",
    "CALL_STALE_HOURS",
    "CALL_RUNNING_STALE_HOURS",
    "PROJECTION_MARKER",
    "FAMILIES",
    "KNOWN_HARNESSES",
    "PARITY_ISSUE_TYPES",
    "APPROVAL_MODES",
    "SCHEMA_TYPES",
    "UNSAFE_FIELD_PATTERN",
    "HIGH_RISK_COMMAND_PATTERNS",
    "DEFAULT_TOOLS",
    "DEFAULT_TOOL_SOURCE_TEXTS",
    "DEFAULT_RUNTIMES",
    "DEFAULT_POLICY",
    "config_path",
    "calls_path",
    "runs_path",
    "checkpoints_path",
    "runtimes_config_path",
    "runtime_state_path",
    "policy_path",
    "parity_closeouts_path",
    "_parse_iso_datetime",
    "_file_hash",
    "_text_hash",
    "_short",
    "_as_path",
    "_path_within_target",
    "_format_inline_list",
    "_format_inline_table",
    "_format_toml_key",
    "_format_toml_object",
    "_format_tool_entries",
    "_format_tools_toml",
    "_default_tool_source_text",
    "_ensure_default_tool_sources",
    "_format_runtimes_toml",
    "_format_policy_toml",
    "_read_json",
    "_stable_hash",
    "_now",
    "_write_json",
    "_load_config",
    "_load_runtime_config",
    "_load_policy_config",
    "_policy_decision",
    "_policy_health",
    "_unsafe_fields",
    "_command_parts",
    "_command_resolves",
    "_high_risk_command",
    "_redact_value",
    "_redact_payload",
    "_redact_text",
    "_redact_known_values",
    "_schema_path",
    "_load_schema",
    "_schema_shape_errors",
    "_json_type_matches",
    "_validate_json_value",
    "_render_argument_template",
    "_contract_defined",
    "_contract_summary",
    "_source_fingerprint",
    "_contract_fingerprint",
    "_contract_issues",
    "policy_init",
    "policy_show",
    "policy_doctor",
    "_projection_issue",
    "_tool_issue",
    "_is_parity_issue",
    "_parity_issue_fingerprint",
    "_latest_parity_closeout",
    "_apply_parity_closeout",
    "_find_runtime",
    "_runtime_file",
    "_runtime_pid_path",
    "_runtime_metadata_path",
    "_runtime_health_path",
    "_runtime_log_paths",
    "_read_pid",
    "_process_alive",
    "_read_runtime_metadata",
    "_write_runtime_metadata",
    "_port_in_use",
    "_runtime_cwd",
    "_runtime_status_item",
    "_runtime_payload",
    "_tool_runtime_issues",
    "_start_runtime_payload",
    "_stop_runtime_payload",
    "_restart_runtime_payload",
    "runtime_init",
    "runtime_list",
    "runtime_show",
    "runtime_status",
    "runtime_start",
    "runtime_stop",
    "runtime_restart",
    "runtime_doctor",
    "_managed_header",
    "_managed_yaml_comment",
    "_parse_projection_metadata",
    "_read_projection",
    "_relative_path",
    "_render_projection_body",
    "_yaml_string",
    "_codex_skill_frontmatter",
    "_is_codex_skill_projection",
    "_projection_managed_body",
    "_render_managed_projection",
    "_projection_item",
    "_projection_plan_payload",
    "_inspect_mcp_config",
    "_inspect_tool",
    "_find_tool",
    "_contracts_payload",
    "init",
    "_read_tool_entries",
    "_projection_scope",
    "_gitignore_selection",
    "_scoped_default_tool",
    "defaults",
    "list_tools",
    "show",
    "search",
    "describe",
    "contracts",
    "plan",
    "apply",
    "_describe_payload",
    "_load_args",
    "_call_plan_payload",
    "_read_calls",
    "_write_calls",
    "_call_fingerprint",
    "_call_plan_from_record",
    "_stored_call_fingerprint",
    "_approval_fingerprint",
    "_make_call_record",
    "_queue_call_payload",
    "_resolve_call",
    "_call_current_fingerprints",
    "_call_projection_summary",
    "_runtime_snapshot_for_call",
    "_run_id_for_call",
    "_call_run_blockers",
    "_call_health",
    "call_plan",
    "call_queue",
    "call_list",
    "call_show",
    "_call_review",
    "call_approve",
    "call_reject",
    "call_hold",
    "_checkpoint_paths",
    "_read_checkpoint",
    "_write_checkpoint",
    "_checkpoint_public_summary",
    "_resolve_checkpoint",
    "_normalize_checkpoint",
    "_collect_run_checkpoints",
    "_checkpoint_expired",
    "_mcp_jsonrpc_requests",
    "_parse_mcp_responses",
    "_mcp_response_by_id",
    "_mcp_tool_list_contains",
    "_run_mcp_call",
    "_write_run_receipt",
    "_run_receipt_paths",
    "_read_run_receipt",
    "_run_sort_key",
    "_run_public_summary",
    "_run_history_payload",
    "_resolve_run_receipt",
    "_replay_plan_payload",
    "_replay_call_payload",
    "_log_path_exists",
    "_run_history_health",
    "_next_approved_call",
    "_run_call_payload",
    "call_run",
    "run_list",
    "run_show",
    "run_latest",
    "run_replay",
    "_checkpoint_resume_blockers",
    "_checkpoint_payload",
    "_checkpoint_health",
    "_resume_checkpoint_payload",
    "checkpoint_list",
    "checkpoint_show",
    "_checkpoint_review",
    "checkpoint_approve",
    "checkpoint_reject",
    "checkpoint_resume",
    "_catalog_payload",
    "_packs_root",
    "_packs_archive_root",
    "_tool_pack_payload",
    "_tool_pack_evidence_fingerprint",
    "pack_build",
    "_tool_packs",
    "_sync_plan_summary",
    "_tool_pack_health",
    "pack_list",
    "_find_tool_pack",
    "pack_show",
    "pack_archive",
    "pack_import",
    "sync_plan",
    "sync_apply",
    "health",
    "_issue_records",
    "doctor",
    "import_issues",
    "parity_status",
    "parity_closeout",
)


def test_facade_exposes_externally_referenced_symbols():
    missing = [name for name in EXPECTED_FACADE_SYMBOLS if not hasattr(tools_cmd, name)]
    assert missing == []


def test_facade_submodules_importable():
    from brigade.tools_cmd import (
        calls,
        catalog_health,
        catalog_manage,
        checkpoint_store,
        checkpoints,
        config,
        constants,
        helpers,
        issues,
        mcp,
        packs,
        paths,
        projections,
        runs,
        runtimes,
        safety,
        status,
    )

    modules = (
        calls,
        catalog_health,
        catalog_manage,
        checkpoint_store,
        checkpoints,
        config,
        constants,
        helpers,
        issues,
        mcp,
        packs,
        paths,
        projections,
        runs,
        runtimes,
        safety,
        status,
    )
    for module in modules:
        assert module.__name__.startswith("brigade.tools_cmd.")


def test_status_health_uses_live_catalog_and_pack_modules(monkeypatch, tmp_path):
    catalog_payload = {
        "config_path": str(tmp_path / ".brigade" / "tools.toml"),
        "valid": True,
        "tool_count": 1,
        "raw_issue_count": 0,
        "issue_count": 0,
        "top_issue": None,
        "issues": [],
        "parity": {"quieted_issue_count": 0},
        "call_queue": {"pending_count": 7},
        "run_history": {"run_count": 3},
        "checkpoints": {"checkpoint_count": 2},
        "runtimes": {"runtime_count": 1},
        "policy": {"enabled": True},
    }
    pack_health = {"pack_count": 5}
    sync_plan = {"projection_count": 11}

    monkeypatch.setattr(tools_cmd.status.catalog_health, "_catalog_payload", lambda target: catalog_payload)
    monkeypatch.setattr(tools_cmd.status.packs_mod, "_tool_pack_health", lambda target: pack_health)
    monkeypatch.setattr(tools_cmd.status.packs_mod, "_sync_plan_summary", lambda target: sync_plan)

    payload = tools_cmd.health(tmp_path)

    assert payload["call_queue"] == {"pending_count": 7}
    assert payload["packs"] == pack_health
    assert payload["sync_plan"] == sync_plan
