"""Characterize Phase 257 command-family facades."""

from __future__ import annotations

import importlib
from pathlib import Path
from types import ModuleType

import pytest

FAMILIES = {
    "daily_cmd": {
        "facade": "brigade.daily_cmd",
        "modules": [
            "config",
            "candidates",
            "approvals",
            "status_plan",
            "run_loop",
            "telemetry",
            "hardening",
            "closeout",
        ],
        "path": "src/brigade/daily_cmd",
    },
    "center_cmd": {
        "facade": "brigade.center_cmd",
        "modules": ["schema", "core", "readiness", "reports", "report_review", "actions"],
        "path": "src/brigade/center_cmd",
    },
    "security_cmd": {
        "facade": "brigade.security_cmd",
        "modules": [
            "models",
            "config",
            "reports",
            "enrichment",
            "suppression",
            "template_audit",
            "scan_engine",
            "commands",
        ],
        "path": "src/brigade/security_cmd",
    },
    "handoff_cmd": {
        "facade": "brigade.handoff_cmd",
        "modules": ["models", "inspect", "linting", "migrate", "drafts", "receipts", "issues", "sources"],
        "path": "src/brigade/handoff_cmd",
    },
    "release_cmd": {
        "facade": "brigade.release_cmd",
        "modules": ["paths", "install_smoke", "ci", "evidence", "candidate", "candidate_audit", "schema", "commands"],
        "path": "src/brigade/release_cmd",
    },
    "work_cmd.session": {
        "facade": "brigade.work_cmd.session",
        "modules": ["lifecycle", "brief", "tasks", "run_status"],
        "path": "src/brigade/work_cmd/session",
    },
    "cli.work": {
        "facade": "brigade.cli.work",
        "modules": ["register", "dispatch", "phases"],
        "path": "src/brigade/cli/work",
    },
}

EXPECTED_SYMBOLS = {
    "daily_cmd": (
        "SCHEMA_VERSION",
        "RUN_STATUSES",
        "APPROVAL_STATUSES",
        "PREFERRED_MODES",
        "RISK_LEVELS",
        "DEFAULT_CONFIG",
        "DEFAULT_STATUS_SECTION_TIMEOUT_SECONDS",
        "_DailyStatusSectionTimeout",
        "_daily_root",
        "_config_path",
        "_plans_root",
        "_runs_root",
        "_approvals_root",
        "_approvals_archive_root",
        "_repairs_root",
        "_unblocks_root",
        "_telemetry_root",
        "_hardening_root",
        "_hardening_closeouts_root",
        "HARDENING_WORKSTREAMS",
        "HARDENING_PHASE_TITLES",
        "IMPLEMENTED_HARDENING_PHASES",
        "_hardening_phases",
        "_schema",
        "_schemas",
        "_write_config",
        "_load_config",
        "_validate_config",
        "_safe_text",
        "_fingerprint",
        "_slug",
        "_status_section_timeout_seconds",
        "_status_section_check",
        "_bounded_status_call",
        "_priority_score",
        "_candidate",
        "_pending_task_candidates",
        "_pending_import_candidates",
        "_center_action_candidates",
        "_readiness_candidates",
        "_daily_readiness_finding",
        "_daily_readiness_payload",
        "_handoff_ingest_candidates",
        "_health_issue_candidates",
        "_notification_candidates",
        "_report_candidate",
        "_phase_ledger_action_candidates",
        "_phase_ledger_issue_candidates",
        "_phase_ledger_issues_captured_by_report",
        "_phase_session_candidates",
        "_all_candidates",
        "_apply_preferred_mode",
        "_selected",
        "_adapter_for",
        "_remote_mutation_reason",
        "_candidate_blockers",
        "_candidate_explanation",
        "_adapter_result",
        "_config_fingerprint",
        "_approval_id",
        "_approval_path",
        "_read_approvals",
        "_write_approval",
        "_find_approval",
        "_matching_approvals",
        "_ensure_approval",
        "_current_action_for_approval",
        "_approval_blockers",
        "_consume_approval",
        "_config_blockers",
        "_evidence_blockers",
        "_parse_time",
        "_is_stale",
        "_age_hours",
        "_daily_center_status_payload",
        "_daily_security_health",
        "status_payload",
        "status",
        "plan_payload",
        "plan",
        "_review_payload",
        "review",
        "_latest_run",
        "_iter_receipts",
        "_latest_plan",
        "_resolve_plan",
        "_record_run",
        "_record_telemetry_event",
        "_invoke_context_build",
        "_blocked_run",
        "run",
        "approvals_payload",
        "approvals_list",
        "approvals_show",
        "_review_approval",
        "approvals_approve",
        "approvals_reject",
        "approvals_hold",
        "approvals_compare_payload",
        "approvals_compare",
        "approvals_archive",
        "init",
        "schema",
        "history_payload",
        "history",
        "show",
        "health",
        "doctor",
        "protocol_payload",
        "protocol",
        "_repair_suggestions",
        "repair_payload",
        "repair",
        "unblock_payload",
        "unblock",
        "resume",
        "_telemetry_events",
        "telemetry_payload",
        "telemetry",
        "telemetry_doctor",
        "hardening_plan_payload",
        "hardening_plan",
        "_hardening_finding",
        "_latest_hardening_closeout",
        "_hardening_quieted_findings",
        "_adapter_result_is_normalized",
        "_plan_explanations_are_complete",
        "hardening_audit_payload",
        "hardening_audit",
        "hardening_import_issues",
        "hardening_closeout",
        "_changed_files_summary",
        "_verification_expectation",
        "_write_handoff",
        "closeout",
    ),
    "center_cmd": (
        "SCHEMA_VERSION",
        "SCHEMA_MANIFEST_VERSION",
        "REPORT_STALE_HOURS",
        "ACTION_STATUSES",
        "ACTION_PENDING_STALE_HOURS",
        "ACTION_ACTIVE_STALE_HOURS",
        "ACTION_DEFERRED_STALE_HOURS",
        "ACTION_DONE_ARCHIVE_HOURS",
        "READINESS_STATUSES",
        "CENTER_REQUIRED_SCHEMA_IDS",
        "CENTER_REQUIRED_ITEM_FIELDS",
        "_parse_time",
        "_path_label",
        "_receipt_reference_exists",
        "_schema",
        "_action_schema",
        "_schema_field",
        "_center_schema_manifest_schemas",
        "_center_schema_manifest",
        "_unsafe_reference",
        "_center_contract_health",
        "_git_value",
        "_git_snapshot",
        "_item",
        "_iter_json_files",
        "_actions_root",
        "_actions_path",
        "_actions_archive_path",
        "_read_actions",
        "_read_action_archive",
        "_write_actions",
        "_append_action_archive",
        "_activity",
        "_reviews",
        "status_payload",
        "status",
        "schema",
        "activity",
        "reviews",
        "templates",
        "_readiness_root",
        "_readiness_archive_root",
        "_readiness_waivers_path",
        "_write_jsonl",
        "_readiness_waivers",
        "_active_readiness_waivers",
        "_readiness_finding",
        "_readiness_safe_text",
        "_readiness_findings",
        "_readiness_payload",
        "_readiness_receipts",
        "_latest_readiness",
        "readiness_health",
        "readiness_plan",
        "readiness_closeout",
        "_readiness_checklist_markdown",
        "readiness_list",
        "_resolve_readiness",
        "readiness_show",
        "readiness_import_issues",
        "_reports_root",
        "_reports_archive_root",
        "_report_diffs_root",
        "_report_json_path",
        "_read_report",
        "_reports",
        "latest_report",
        "_report_diffs",
        "latest_report_diff",
        "_resolve_report",
        "_receipt_references",
        "_item_key",
        "_fingerprint_payload",
        "_report_payload",
        "_suggested_report_commands",
        "_report_markdown",
        "_review_groups",
        "_action_plan",
        "_report_html",
        "_write_report_bundle",
        "report_health",
        "report_plan",
        "report_build",
        "report_list",
        "report_show",
        "report_archive",
        "report_review",
        "_receipt_newer_than_report",
        "_report_queue_changed",
        "_report_review_map",
        "_is_blocker_item",
        "_missing_receipt_refs",
        "_report_diff_payload",
        "report_diff",
        "report_compare",
        "report_closeout",
        "_report_review_status",
        "_report_reviewed_at",
        "_action_priority_rank",
        "_planned_actions",
        "_find_action",
        "_action_counts",
        "_action_age_hours",
        "_action_policy_issue",
        "_action_policy_issues",
        "actions_health",
        "actions_doctor",
        "_action_policy_import_record",
        "actions_import_issues",
        "actions_plan",
        "actions_build",
        "actions_list",
        "actions_show",
        "_set_action_status",
        "actions_start",
        "actions_done",
        "actions_defer",
        "actions_archive_completed",
    ),
    "security_cmd": (
        "SEVERITY_ORDER",
        "CONFIG_REL_PATH",
        "ARTIFACTS_REL_PATH",
        "POLICIES",
        "SCAN_PROFILES",
        "SECURITY_CHECKS",
        "SKIP_DIRS",
        "SKIP_PREFIXES",
        "TEXT_SUFFIXES",
        "SECRET_VALUE_RE",
        "PLAINTEXT_PASSWORD_RE",
        "PRIVATE_KEY_RE",
        "ENV_ASSIGNMENT_RE",
        "REMOTE_SHELL_RE",
        "DESTRUCTIVE_RE",
        "UNPINNED_NPX_RE",
        "ENV_DUMP_RE",
        "UNPINNED_ACTION_RE",
        "PINNED_ACTION_RE",
        "PYTHON_URL_DEP_RE",
        "TOML_TABLE_RE",
        "HTTP_MCP_RE",
        "AUTO_APPROVE_RE",
        "MCP_SENSITIVE_ARG_RE",
        "MCP_BROAD_PATHS",
        "MCP_HIGH_RISK_COMMANDS",
        "MCP_SERVER_COUNT_WARN",
        "MCP_SHELL_META_RE",
        "FINGERPRINT_RE",
        "GITHUB_ACTION_FLOATING_REFS",
        "INDICATOR_URL_RE",
        "INDICATOR_NPX_RE",
        "INDICATOR_GITHUB_ACTION_RE",
        "ENRICHMENT_PROVIDERS",
        "ENRICHMENT_MARKDOWN_START",
        "ENRICHMENT_MARKDOWN_END",
        "TEMPLATE_AUDIT_ROOTS",
        "TEMPLATE_PRIVATE_PATH_RE",
        "TEMPLATE_PRIVATE_URL_RE",
        "TEMPLATE_ALLOWLIST_RE",
        "HARNESS_ROOTS",
        "HARNESS_PATH_KEYS",
        "HARNESS_COMMAND_KEYS",
        "HARNESS_URL_KEYS",
        "HARNESS_ALLOWED_URL_RE",
        "SESSION_CHAT_PARTS",
        "SecurityEnrichmentConfig",
        "SecurityConfig",
        "EffectivePolicy",
        "config_path",
        "default_artifacts_dir",
        "_closeouts_root",
        "_read_closeouts",
        "inspect_evidence_bundle",
        "_parse_toml_value",
        "_read_toml_object",
        "load_config",
        "_parse_string_list",
        "_parse_enrichment_config",
        "_effective_policy",
        "write_default_config",
        "_toml_string",
        "write_config",
        "_load_config_or_default",
        "_clean_reason",
        "_gitignore_selection",
        "fix",
        "_load_report",
        "_load_report_file",
        "_report_findings_for_review",
        "review",
        "findings",
        "_diff_finding_key",
        "diff",
        "sarif",
        "_resolve_finding_record",
        "show",
        "_load_enrichment_payload",
        "_indicator_source",
        "_add_indicator",
        "_extract_enrichment_indicators",
        "_local_enrich",
        "_cache_file",
        "_read_enrichment_cache",
        "_write_enrichment_cache",
        "_misp_query_indicator",
        "_misp_attributes",
        "_misp_enrich",
        "_render_enrichment_markdown",
        "_render_enrichment_summary",
        "_upsert_report_enrichment_summary",
        "write_enrichment_bundle",
        "enrichment_health",
        "enrich",
        "suppress",
        "unsuppress",
        "suppression_health",
        "_short",
        "_is_placeholder",
        "_redact_secret_evidence",
        "_contains_private_key_material",
        "_template_relpath",
        "_template_audit_finding",
        "template_privacy_payload",
        "harness_wiring_payload",
        "template_audit",
        "_rule_id",
        "_line_number_for",
        "_is_mcp_document",
        "_server_timeout",
        "_scan_mcp_document",
        "_is_harness_wiring_document",
        "_scan_harness_wiring_document",
        "_scan_harness_value",
        "_scan_harness_string",
        "_harness_semantic_key",
        "_harness_evidence",
        "_harness_line_number",
        "_scan_harness_path_value",
        "_scan_harness_command_value",
        "_scan_harness_url_value",
        "_first_npx_package",
        "_scan_package_json",
        "_scan_github_actions",
        "_scan_python_project",
        "_python_url_dependency_candidate",
        "_iter_scan_files",
        "_surface_for",
        "_confidence_for",
        "_is_session_chat_path",
        "_secret_response_options",
        "_fingerprint",
        "_finding",
        "_is_security_scanner_literal",
        "_scan_line",
        "_path_matches_any",
        "_severity_selected",
        "_filter_findings",
        "_scan_handoff_inboxes",
        "scan_target",
        "_should_fail",
        "_import_findings",
        "_render_markdown_report",
        "_sarif_level",
        "_sarif_report",
        "write_evidence_bundle",
        "_config_payload",
        "show_config",
        "health",
        "doctor",
        "closeout",
        "scan",
        "init",
    ),
    "handoff_cmd": (
        "OK",
        "WARN",
        "FAIL",
        "WRITER_INBOXES",
        "IGNORED_HANDOFF_NAMES",
        "DEFAULT_STALE_AFTER_MINUTES",
        "HANDOFF_DRAFT_STALE_HOURS",
        "BACKLOG_STALE_SECONDS",
        "MAX_INGESTOR_WARNING_SIGNALS",
        "CARD_ACTIONS",
        "NO_CARD_ACTION",
        "HANDOFF_ACTIONS",
        "CARD_TARGET_PATTERN",
        "DOCUMENT_TARGETS",
        "DOCUMENT_TARGET_PREFIXES",
        "DEFAULT_DRAFT_INBOX",
        "DEFAULT_DRAFT_DOCUMENT",
        "DEFAULT_WARNING_PATTERNS",
        "ISSUE_SOURCE",
        "WatchedInbox",
        "IngestorConfig",
        "SourceConfig",
        "InboxHealth",
        "IngestorHealth",
        "HandoffIssue",
        "HandoffLintResult",
        "HandoffHealth",
        "HandoffDraft",
        "default_sources_path",
        "inspect",
        "doctor_checks",
        "collect_issues",
        "lint",
        "_guard_handoff_path",
        "lint_targets",
        "lint_file",
        "_LOOSE_FIELD_TEMPLATE",
        "_loose_field",
        "_migrate_extract",
        "migrate",
        "_handoff_state_root",
        "_handoff_archive_root",
        "_handoff_archive_records_path",
        "_handoff_ingest_runs_root",
        "_handoff_closeouts_root",
        "_load_source_config_for_drafts",
        "_draft_inbox_specs",
        "_draft_paths",
        "_path_timestamp",
        "_iso_from_timestamp",
        "_timestamp_id",
        "_normalize_receipt_list",
        "_receipt_path_value",
        "_receipt_target_value",
        "_path_match_keys",
        "_ingest_receipt_path",
        "_normalize_ingest_receipt",
        "_load_ingest_receipt",
        "_ingest_receipts",
        "_ingest_receipt_outcomes",
        "_ingest_outcomes_by_path",
        "_latest_ingest_outcome_for_path",
        "_receipt_summary",
        "_extract_handoff_key_values",
        "_draft_summary",
        "_drafts",
        "_archive_records",
        "_write_archive_records",
        "_append_archive_record",
        "_archive_record_with_ingest_outcome",
        "_refresh_archive_ingest_outcomes",
        "_draft_source_import_issues",
        "draft_queue_payload",
        "_find_draft",
        "_slugify",
        "_read_suggested_content",
        "_draft_inbox_path",
        "_render_bullets",
        "_render_handoff_draft",
        "draft",
        "list_drafts",
        "show_draft",
        "_archive_one",
        "archive_draft",
        "_draft_closeout_fingerprint",
        "closeout",
        "runs",
        "run_show",
        "_safe_label",
        "_select_receipt_drafts",
        "_receipt_payload_for_drafts",
        "_receipt_plan_payload",
        "receipt_plan",
        "receipt_record",
        "reconcile",
        "issues",
        "import_issues",
        "sync_issues",
        "doctor",
        "sources_init",
        "_resolve_lint_path",
        "_pending_handoff_paths",
        "_parse_markdown_sections",
        "_section_value",
        "_lint_card_action",
        "_lint_no_card_action",
        "_valid_document_target",
        "_lint_repair_for_result",
        "_known_local_issue_ids",
        "_close_stale_local_issue_work",
        "_handoff_issue_id",
        "_handoff_issue_category",
        "_covered_warning_summary_ids",
        "_stale_close_reason",
        "_issues_payload",
        "_issue_counts",
        "_dedupe_issues",
        "_filter_issues_by_category",
        "_make_issue",
        "_handoff_issue_source_key",
        "_handoff_issue_fingerprint",
        "_source_config_for_checks",
        "_parse_ingestor_log_issues",
        "_parse_ingestor_log_receipt",
        "_split_outcome_line",
        "_issue_from_log_line",
        "_split_issue_line",
        "_text_for_issue",
        "_repair_for_issue",
        "_looks_unreachable",
        "_looks_no_reply",
        "_looks_malformed",
        "_warning_event",
        "_safe_log_subject",
        "_load_sources",
        "_parse_ingestor_config",
        "_inspect_ingestor",
        "_ingestor_warning_lines",
        "_resolve_source_root",
        "_normalize_inbox",
        "_short",
        "_inspect_inbox",
        "_oldest_pending_age_seconds",
        "_count_pending",
        "_count_processed",
        "_is_watched",
        "_format_seconds",
    ),
    "release_cmd": (
        "OK",
        "WARN",
        "FAIL",
        "RELEASE_CANDIDATE_STALE_HOURS",
        "PHASE_REPORT_STALE_HOURS",
        "RELEASE_PRIVATE_VALUE_RE",
        "RELEASE_PRIVATE_PATH_RE",
        "SCHEMA_MANIFEST_VERSION",
        "INSTALL_SMOKE_STALE_HOURS",
        "INSTALL_SMOKE_STATUSES",
        "INSTALL_SMOKE_MATRIX",
        "CI_DEPRECATION_PATTERNS",
        "CI_DEPRECATED_ACTION_MAJORS",
        "CI_ACTION_REF_RE",
        "_field",
        "_release_root",
        "_release_runs_root",
        "_release_candidates_root",
        "_release_candidates_archive_root",
        "_git",
        "_git_value",
        "_git_state",
        "_latest_work_closeout",
        "_latest_review_closeout",
        "_latest_closeout_json",
        "_security_summary",
        "_changed_files",
        "_docs_warnings",
        "_install_smoke_root",
        "_install_smoke_receipts_path",
        "_normalize_harnesses",
        "_install_smoke_matrix_id",
        "_install_smoke_matrix",
        "_read_install_smoke_receipts",
        "_write_install_smoke_receipts",
        "_install_smoke_record_from_payload",
        "install_smoke_plan",
        "install_smoke_record",
        "install_smoke_list",
        "_resolve_install_smoke_receipt",
        "install_smoke_show",
        "install_smoke_health",
        "install_smoke_doctor",
        "_safe_path_label",
        "_ci_safe_excerpt",
        "_ci_log_paths",
        "_ci_finding",
        "_ci_findings_from_log",
        "_ci_findings_from_workflows",
        "ci_platform_payload",
        "ci_doctor",
        "_ci_import_records",
        "ci_import_issues",
        "_content_guard_available",
        "_content_guard_command",
        "_run_content_guard_check",
        "_read_release_receipt",
        "_release_receipts",
        "_latest_release_receipt",
        "_resolve_release_receipt",
        "_read_candidate",
        "_release_candidates",
        "_latest_candidate",
        "_phase_release_checks",
        "_resolve_candidate",
        "_evidence",
        "_assess",
        "_payload",
        "_payload_with_candidate_health",
        "_write_release_markdown",
        "_candidate_docs_touch",
        "_release_safe_text",
        "_commit_subjects",
        "_changelog_unreleased",
        "_latest_release_or_payload",
        "_candidate_payload",
        "_command_contract_snapshot",
        "_candidate_health",
        "_release_dogfood_health",
        "_schema_manifest_schemas",
        "_latest_fleet_release_train",
        "_schema_manifest",
        "_receipt_ref",
        "_candidate_release_notes",
        "_candidate_publish_plan",
        "_candidate_summary",
        "_write_candidate_bundle",
        "plan",
        "doctor",
        "schema",
        "candidate_plan",
        "candidate_build",
        "candidate_list",
        "candidate_show",
        "candidate_archive",
        "_candidate_bundle_files",
        "_candidate_privacy_issues",
        "_candidate_reference_issues",
        "_candidate_docs_changed_after_build",
        "_candidate_audit_payload",
        "candidate_audit",
        "candidate_import_issues",
        "_receipt_newer_than_candidate",
        "candidate_compare",
        "candidate_closeout",
        "run",
        "runs",
        "show",
    ),
    "work_cmd.session": (
        "_latest_run_next_metadata",
        "_queue_latest_next",
        "_latest_completed_run_path",
        "_resolve_next_task",
        "_render_task_run_prompt",
        "_task_plan_payload",
        "_display_session",
        "_session_task_markdown",
        "_write_session_markdown",
        "_write_work_handoff",
        "_print_dirty",
        "_doctor_ignore_level",
        "_workflow_rule_health",
        "_next_payload",
        "_suggested_command",
        "_pick_fields",
        "_compact_top",
        "_compact_operator_report_latest",
        "_compact_repo_fleet_latest",
        "_compact_health_section",
        "_compact_repo_fleet_health",
        "_brief_payload",
        "_print_bootstrap_line",
        "start",
        "end",
        "note",
        "list_sessions",
        "latest",
        "show",
        "recap",
        "_print_resume_session",
        "resume",
        "brief",
        "tasks",
        "task_add",
        "task_show",
        "task_plan",
        "task_done",
        "next",
        "bootstrap",
        "run",
        "status",
        "doctor",
    ),
    "cli.work": (
        "register",
        "dispatch",
        "_register_phases",
    ),
}


def test_phase257_facades_export_original_top_level_symbols():
    for family, names in EXPECTED_SYMBOLS.items():
        facade = importlib.import_module(FAMILIES[family]["facade"])
        missing = [name for name in names if not hasattr(facade, name)]
        assert missing == [], family


def test_phase257_family_submodules_importable():
    for _family, config in FAMILIES.items():
        for module_name in config["modules"]:
            module = importlib.import_module(f"{config['facade']}.{module_name}")
            assert module.__name__ == f"{config['facade']}.{module_name}"


@pytest.mark.parametrize(
    "module_name",
    [
        "brigade.cli.work.register",
        "brigade.cli.work.dispatch",
        "brigade.daily_cmd.telemetry",
        "brigade.daily_cmd.closeout",
        "brigade.center_cmd.schema",
        "brigade.center_cmd.report_review",
        "brigade.security_cmd.template_audit",
        "brigade.handoff_cmd.inspect",
        "brigade.handoff_cmd.migrate",
        "brigade.handoff_cmd.issues",
        "brigade.release_cmd.candidate_audit",
        "brigade.release_cmd.schema",
        "brigade.work_cmd.session.brief",
        "brigade.work_cmd.session.tasks",
    ],
)
def test_phase257_normal_dotted_imports_bind_modules(module_name):
    namespace: dict[str, object] = {}
    exec(f"import {module_name} as imported_module", namespace)
    assert isinstance(namespace["imported_module"], ModuleType), module_name


@pytest.mark.parametrize(
    ("facade_name", "callable_name", "target_module_name"),
    [
        ("brigade.cli.work", "register", "brigade.cli.work.registration"),
        ("brigade.cli.work", "dispatch", "brigade.cli.work.dispatching"),
        ("brigade.daily_cmd", "telemetry", "brigade.daily_cmd.telemetry_ops"),
        ("brigade.daily_cmd", "closeout", "brigade.daily_cmd.closeout_ops"),
        ("brigade.center_cmd", "report_review", "brigade.center_cmd.report_review_ops"),
        ("brigade.security_cmd", "template_audit", "brigade.security_cmd.template_audit_ops"),
        ("brigade.handoff_cmd", "inspect", "brigade.handoff_cmd.inspect_ops"),
        ("brigade.handoff_cmd", "migrate", "brigade.handoff_cmd.migrate_ops"),
        ("brigade.handoff_cmd", "issues", "brigade.handoff_cmd.issue_ops"),
        ("brigade.release_cmd", "candidate_audit", "brigade.release_cmd.candidate_audit_ops"),
        ("brigade.work_cmd.session", "brief", "brigade.work_cmd.session.briefing"),
        ("brigade.work_cmd.session", "tasks", "brigade.work_cmd.session.task_ops"),
    ],
)
def test_phase257_alias_modules_preserve_callable_facade_exports(
    monkeypatch, facade_name, callable_name, target_module_name
):
    exec(f"import {facade_name}.{callable_name}")
    facade = importlib.import_module(facade_name)
    target = importlib.import_module(target_module_name)
    exported = getattr(facade, callable_name)

    def replacement(*args, **kwargs):
        return ("called", args, kwargs)

    monkeypatch.setattr(target, callable_name, replacement)
    assert isinstance(exported, ModuleType)
    assert exported("value", flag=True) == ("called", ("value",), {"flag": True})


def test_phase257_facade_monkeypatch_reaches_submodule(monkeypatch):
    checks = {
        "daily_cmd": ("_safe_text", "config"),
        "center_cmd": ("_parse_time", "schema_ops"),
        "security_cmd": ("config_path", "config"),
        "handoff_cmd": ("_short", "sources"),
        "release_cmd": ("_git_value", "paths"),
        "work_cmd.session": ("_suggested_command", "briefing"),
        "cli.work": ("dispatch", "dispatching"),
    }
    sentinel = object()
    for family, (name, module_name) in checks.items():
        facade = importlib.import_module(FAMILIES[family]["facade"])
        module = importlib.import_module(f"{FAMILIES[family]['facade']}.{module_name}")
        monkeypatch.setattr(facade, name, sentinel)
        assert getattr(module, name) is sentinel


def test_phase257_production_family_files_stay_under_2000_lines():
    roots = [
        Path("src/brigade/daily_cmd"),
        Path("src/brigade/center_cmd"),
        Path("src/brigade/security_cmd"),
        Path("src/brigade/handoff_cmd"),
        Path("src/brigade/release_cmd"),
        Path("src/brigade/work_cmd/session"),
        Path("src/brigade/cli/work"),
    ]
    files = []
    for root in roots:
        if root.is_dir():
            files.extend(sorted(root.glob("*.py")))
        else:
            files.append(root.with_suffix(".py"))
    oversized = {
        str(path): len(path.read_text(encoding="utf-8").splitlines())
        for path in files
        if path.is_file() and len(path.read_text(encoding="utf-8").splitlines()) > 2000
    }
    assert oversized == {}
